---
title: "lab09"
author: "sl"
date: "`r Sys.Date()`"
output: 
     pdf_document: default
     word_document: default
     html_document: default
     github_document:
        html_preview: false
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 2.

Create a n x k dataset with all its entries distributed poission with mean lambda
```{r}
set.seed(1235)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}
f1 <- fun1(1000,4)
mean(f1)
#f1 <- fun1(10000,4)
#f1 <- fun1(50000,4)

fun1alt <- function(n = 100, k = 4, lambda = 4) {
  # YOUR CODE HERE
  
  x <- matrix( rpois(n*k, lambda), ncol = 4)
  
  return(x)
}
f1 <- fun1alt(50000,4)


# Benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)
```


```{r}
d <- matrix(1:16, ncol = 4)
d
```

```{r}
diag(d)
d[2,1]
d[c(1,6,11,16)]
cbind(1:4,1:4)
d[cbind(1:4,1:4)]
```

## Problem 3.
Find the column max (hint: Checkout the function max.col()).
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
M <- matrix(runif(12), ncol = 4)
M


# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
}
fun2(x=M)


fun2alt <- function(x) {
  # YOUR CODE HERE
  idx <- max.col(t(x))
  x[cbind(idx,1:4)]
}
fun2alt(x=M)

x <- matrix(rnorm(1e4), nrow=10)


# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)

```





